
# Login page
LOGIN_PASSWORD = '//*[@id="root"]/div/div[2]/div/div/div[2]/form/div[2]/div[2]/input'
LOGIN_BUTTON = '//*[@id="root"]/div/div[2]/div/div/div[2]/form/div[4]/button'
LOGIN_ERROR_MESSAGE = '/html/body/div[2]/div/div[2]/div/div[2]/div/div[1]/div[2]/div[1]/h3'

#LANDING PAGE
LANDING_PAGE_HEADER = '//*[@id="root"]/div/div[2]/div[2]/h1'
LANDING_PAGE_PROFILE = '/html/body/div[2]/div/div[2]/div[1]/div/div/div[2]/div[7]/div[1]/button'
LANDING_PAGE_LOGOUT = '/html/body/div[2]/div/div[2]/div[1]/div/div/div[2]/div[7]/div[2]/button'

#Toast Message
TOAST_MESSAGE = '/html/body/div[2]/div/div[2]/div[3]/div/div/div[2]/div[2]'
TOAST_MESSAGE_CROSS = '/html/body/div[2]/div/div[2]/div[3]/div/div/div[2]/div[1]/div/div/svg'
TOAST_ALERT='/html/body/div[2]/div/div[2]/div[3]/div/div/div[2]/div[2]'
TOAST_MESSAGE_CLOSE='/html/body/div[2]/div/div[2]/div[3]/div/div/div[2]/div[1]/div/div'

#Field Personnel Page
FIELD_PERSONNEL_VISIBILITY_COLUMN_BTN='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/button'
FIELD_PERSONNEL_UNCHECKS_NAME='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/label'
FIELD_PERSONNEL_UNCHECKS_NO='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/input'
FIELD_PERSONNEL_UNCHECKS_CONTACT_NUMBER='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[3]/input'
FIELD_PERSONNEL_UNCHECKS_SKILLSET='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[4]/input'
FIELD_PERSONNEL_UNCHECKS_ZONES='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[7]/input'
FIELD_PERSONNEL_UNCHECKS_CONTRACT_DATE='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[8]/input'
FIELD_PERSONNEL_UNCHECKS_STATUS='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[9]/input'
FIELD_PERSONNEL_UNCHECKS_ACTION='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[10]/input'

FIELD_PERSONNEL_CHECKS_NAME='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/label'
FIELD_PERSONNEL_CHECKS_NO='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/input'
FIELD_PERSONNEL_CHECKS_CONTACT_NUMBER='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[3]/input'
FIELD_PERSONNEL_CHECKS_SKILLSET='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[4]/input'
FIELD_PERSONNEL_CHECKS_ZONES='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[7]/input'
FIELD_PERSONNEL_CHECKS_CONTRACT_DATE='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[8]/input'
FIELD_PERSONNEL_CHECKS_STATUS='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[9]/input'
FIELD_PERSONNEL_CHECKS_ACTION='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[10]/input'

FIELD_PERSONNEL_SEARCH='/html/body/div[2]/div/div[2]/div[2]/div[1]/div[1]/div/input'
FIELD_PERSONNEL_RESULT='/html/body/div[2]/div/div[2]/div[2]/h1'
FIELD_PERSONNEL_SEARCH_OPTION='/html/body/div[2]/div/div[2]/div[2]/div[1]/div[1]/div/input'
FIELD_PERSONNEL_SEARCH_CLOSE='/html/body/div[2]/div/div[2]/div[2]/div[1]/div[1]/div/div'
FIELD_PERSONNEL_SEARCH_ERROR='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div/div[2]/div[1]/h3'
FIELD_PERSONNEL_ADD_BUTTON='//*[@id="root"]/div/div[2]/div[2]/div[1]/div[2]/button[1]'
FIELD_PERSONNEL_NAME='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[1]/div[1]/div/input'
FIELD_PERSONNEL_CONTACT_NUMBER='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[1]/div[2]/div/input'
FIELD_PERSONNEL_EMAIL='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[2]/div/input'
FIELD_PERSONNEL_SKILLSET_DROP_DOWN='//*[@id="root"]/div/div[2]/div[2]/form/div[3]/div[1]/div/div/div[1]'
FIELD_PERSONNEL_SKILLSET_DROP_DOWN_CLEAR='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div[1]/div/div/div[1]/div[2]/div[1]'
FIELD_PERSONNEL_ZONES_DROP_DOWN='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div[2]/div/div/div[1]/div[2]/div'
FIELD_PERSONNEL_ZONES_DROP_DOWN_CLEAR='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div[2]/div/div/div[1]/div[2]/div[1]'
FIELD_PERSONNEL_CONTRACT_START_DATE_OPTION= '/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[1]/div/div[1]/input'
FIELD_PERSONNEL_CALENDAR_MM_YYYY='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[1]/div/div[2]/div/div[1]/div/button[2]'
#FIELD_PERSONNEL_CALENDAR_PREV_BTN='/html/body/div[2]/div/div[2]/div[2]/form/div[4]/div[1]/div/div[2]/div/div[1]/div/button[1]'
FIELD_PERSONNEL_CONTRACT_START_DATE_SELECT='//*[@id="root"]/div/div[2]/div[2]/form/div[1]/div[3]/div[1]/div/div[2]/div/div[2]/div[2]/span[2]'
FIELD_PERSONNEL_CONTRACT_END_DATE_OPTION='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[2]/div/div[1]/input'
#FIELD_PERSONNEL_CALENDAR_END_PREV_BTN='/html/body/div[2]/div/div[2]/div[2]/form/div[4]/div[2]/div/div[2]/div/div[1]/div/button[1]'
FIELD_PERSONNEL_CALENDAR_END_MM_YYYY='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[2]/div/div[2]/div/div[1]/div/button[2]'
FIELD_PERSONNEL_CONTRACT_END_DATE_SELECT='//*[@id="root"]/div/div[2]/div[2]/form/div[1]/div[3]/div[2]/div/div[2]/div/div[2]/div[2]/span[16]'
FIELD_PERSONNEL_START_NEXT_BTN ='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[1]/div/div[2]/div/div[1]/div/button[3]'
FIELD_PERSONNEL_END_NEXT_BTN ='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[3]/div[2]/div/div[2]/div/div[1]/div/button[3]'                          

FIELD_PERSONNEL_CONTRACT_START_DATE_OPTION_YEAR='/html/body/div[2]/div/div[2]/div[2]/form/div[4]/div[1]/div/div[2]/div/div[2]/div'
FIELD_PERSONNEL_CONTRACT_START_DATE_OPTION_MONTH='//*[@id="root"]/div/div[2]/div[2]/form/div[4]/div[1]/div/div[2]/div/div[2]/div'
FIELD_PERSONNEL_CONTRACT_START_DATE_OPTION_DATE='/html/body/div[2]/div/div[2]/div[2]/form/div[4]/div[1]/div/div[2]/div/div[2]/div[2]'

FIELD_PERSONNEL_SHIFT_DROP_DOWN='/html/body/div[2]/div/div[2]/div[2]/form/div[5]/div/div/div/div/div[2]/div'
FIELD_PERSONNEL_STATUS_ACTIVE='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[4]/div/div/div[2]/input'
FIELD_PERSONNEL_STATUS_INACTIVE='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[4]/div/div/div[1]/input'
FIELD_PERSONNEL_SAVE_BUTTON='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[5]/button[2]'
FIELD_PERSONNEL_ERROR_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div[1]/div/div/span'

FIELD_PERSONNEL_ALERT_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div/div[2]/div[1]/h3'
FIELD_PERSONNEL_CANCEL_BUTTON='/html/body/div[2]/div/div[2]/div[2]/div[4]/div/div/div[2]/button[1]'
FIELD_PERSONNEL_PENCIL_ICON='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div[1]/table/tbody/tr[1]/td[8]/div/a'
FIELD_PERSONNEL_UPDATED_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[1]/div/div/div[2]/div[1]/h3' 

FIELD_PERSONNEL_BLOCK_ICON_BUTTON='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div[1]/table/tbody/tr[1]/td[8]/div/div[2]'
FIELD_PERSONNEL_POPUP_MESSEGE='/html/body/div[2]/div/div[2]/div[2]/div[4]/div/div/div[2]/button[2]'
FIELD_PERSONNEL_UPDATED_BLOCK_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div[1]/table/tbody/tr[1]/td[7]/div'
FIELD_PERSONNEL_SKILLSET = "//*[text()='Hyundai']"
FIELD_PERSONNEL_ZONE = "//*[text()='T1']"
FIELD_PERSONNEL_SHIFT = "//*[text()='Morning Shift']"

#Skillset

#Total visibility column
SKILLSET_VISIBILITY_COLUMN_BTN='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/button'
SKILLSET_UNCHECKS_NAME='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/input'
SKILLSET_UNCHECKS_NO='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[1]/input'
SKILLSET_UNCHECKS_CATEGORY='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[3]/input'
SKILLSET_UNCHECKS_SUBCATEGORY='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[4]/input'
SKILLSET_UNCHECKS_REMARKS='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[5]/input'
SKILLSET_UNCHECKS_ACTION='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[6]/input'

SKILLSET_CHECKS_NAME='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[2]/input'
SKILLSET_CHECKS_NO='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[1]/input'
SKILLSET_CHECKS_CATEGORY='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[3]/input'
SKILLSET_CHECKS_SUBCATEGORY='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[4]/input'
SKILLSET_CHECKS_REMARKS='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[5]/input'
SKILLSET_CHECKS_ACTION='/html/body/div[2]/div/div[2]/div[2]/div[3]/div[2]/div/div[6]/input'

SKILLSET_SEARCH='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[1]/div/input'
SKILLSET_RESULT='//*[@id="root"]/div/div[2]/div[2]/h1'
SKILLSET_SEARCH_ERROR='/html/body/div[2]/div/div[2]/div[2]/div[4]/div/div/div/div[2]/div[1]/h3'
SKILLSET_ADD_SKILLSET_BUTTON='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/button[1]'
SKILLSET_NAME='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div/input'
SKILLSET_CATEGORY='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div/input'
SKILLSET_SUB_CATEGORY='/html/body/div[2]/div/div[2]/div[2]/form/div[2]/div/input'
SKILLSET_REMARKS='/html/body/div[2]/div/div[2]/div[2]/form/div[4]/textarea'
SKILLSET_SAVE='/html/body/div[2]/div/div[2]/div[2]/form/div[6]/button[2]'
SKILLSET_ALERT_MESSAGE='/div/div/div/div[2]/div[1]/h3'
SKILLSET_ERROR_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div/div/span'
SKILLSET_PENCIL_ICON='/html/body/div[2]/div/div[2]/div[2]/div[4]/div/div/div[1]/table/tbody/tr[2]/td[6]/div/a'
SKILLSET_DELETE_ICON_BUTTON='/html/body/div[2]/div/div[2]/div[2]/div[4]/div/div/div[1]/table/tbody/tr[2]/td[6]/div/div'
SKILLSET_POPUP_MESSEGE='/html/body/div[2]/div/div[2]/div[2]/div[5]/div/div/div[2]/button[2]'
SKILLSET_UPDATED_BLOCK_MESSAGE='/html/body/div[2]/div/div[2]/div[3]/div/div/div[2]'

#Asset Page
ASSET_VISIBILITY_COLUMN_BTN = '/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/button'
ASSET_LICENSE_PLATE_CHECKBOX= '/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[4]/input'
ASSET_VEHICLE_MANUFACTURER_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[1]/input'
ASSET_VEHICLE_MODEL_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/input'
ASSET_VEHICLE_NAME_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[3]/input'
ASSET_VEHICLE_TYPE_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[5]/input'
ASSET_START_LOCATION_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[6]/input'
ASSET_END_LOCATION_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[7]/input'
ASSET_FIELD_PERSONNEL_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[8]/input'
ASSET_STATUS_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[9]/input'
ASSET_ACTION_CHECKBOX='/html/body/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[10]/input'

ASSET_SEARCH = '//input[@placeholder="Search license plate"]'
ASSET_RESULT = '/html/body/div[2]/div/div[2]/div[2]/h1'
ASSET_SEARCH_ERROR='/html/body/div[2]/div/div[2]/div[2]/div[3]/div/div/div/div[2]/div[1]/h3'

ASSET_ADD_ASSET_BUTTON='//*[@id="root"]/div/div[2]/div[2]/div[1]/div[2]/button[2]'
ASSET_VEHICLE_MANUFACTURER ='/html/body/div[2]/div/div[2]/div[2]/form/div[1]/div/input'
ASSET_VEHICLE_MODEL='//*[@id="root"]/div/div[2]/div[2]/form/div[2]/div/input'
ASSET_VEHICLE_TYPE_DROP_DOWN='/html/body/div[2]/div/div[2]/div[2]/form/div[3]/div/div/div[1]/div[2]'
ASSET_VEHICLE_TYPE='//*[@value="2"]'
ASSET_VEHICLE_COMPANY='//*[@id="root"]/div/div[2]/div[2]/form/div[4]/div/input'
ASSET_REGISTER_NUMBER='//*[@id="root"]/div/div[2]/div[2]/form/div[5]/div/input'
ASSET_DEPOT_START='//*[@id="root"]/div/div[2]/div[2]/form/div[6]/div[1]/div/div/div'
ASSET_DEPOT_START_OPTION='//*[@id="root"]/div/div[2]/div[2]/form/div[6]/div[1]/div/div/div'
ASSET_DEPOT_END='/html/body/div[2]/div/div[2]/div[2]/form/div[6]/div[2]/div/div/div/div[2]/div'
ASSET_DEPOT_END_OPTION='//input[@value="1"]'
ASSET_LICENSE_PLATE='//*[@id="root"]/div/div[2]/div[2]/form/div[7]/div[1]/div/input'
ASSET_STATUS_ACTIVE='/html/body/div[2]/div/div[2]/div[2]/form/div[7]/div[2]/div/div/div[2]/input'
ASSET_STATUS_INACTIVE='/html/body/div[2]/div/div[2]/div[2]/form/div[7]/div[2]/div/div/div[1]/input'
ASSET_SAVE_BUTTON='/html/body/div[2]/div/div[2]/div[2]/form/div[9]/div/button[2]'
ASSET_ALERT_MESSAGE='/div/div/div/div[2]/div[2]'
ASSET_PENCIL_ICON ='//*[@href="/pre-mission/asset/edit/4808"]'
#ASSET_RESULT_MESSAGE ='/html/body/div[2]/div/div[2]'
#ASSET_ALERT_MESSAGE_CLOSE='//*[@id="root"]/div/div[2]/div[2]/div[1]/div[2]/button[2]'
ASSET_ERROR_MESSAGE='/html/body/div[2]/div/div[2]/div[2]/form/div[7]/div[1]/div/div/span'
ASSET_CANCEL_BUTTON='//*[@id="root"]/div/div[2]/div[2]/form/div[9]/div/button[1]'
ASSET_UPLOAD_FILE_BUTTON='//*[@id="root"]/div/div[2]/div[2]/div[1]/div[2]/button[1]'
ASSET_DOWNLOAD_FILE_BUTTON='/html/body/div[3]/div/div/div/div[2]/div/div/div[3]/button'
ASSET_CLICK_OPTION='/html/body/div[3]/div/div/div/div[2]/div/div/div[4]/label/div/div/span[1]/span'
ASSET_IMPORT_OPTION='/html/body/div[3]/div/div/div/div[2]/div/div/div[5]/div[2]/button'
ASSET_SUCCESS_MESSAGE='/div/div/div/div[2]/div[2]'
ASSET_EDIT_BUTTON='//*[@id="root"]/div/div[2]/div[2]/div[3]/div/div/div[1]/table/tbody/tr[5]/td[8]/div/a[2]'
ASSET_UPDATE_MESSAGE='/div/div/div/div[2]/div[2]'
ASSET_BLOCK_ICON_BUTTON='//*[@class="w-6 h-6 cursor-pointer"]'
ASSET_BLOCK_POPUP_MESSEGE='//*[@id="root"]/div/div[2]/div[2]/div[4]/div/div/div[2]/button[2]'
ASSET_UPDATED_BLOCK_MESSAGE='/div/div/div/div[2]/div[1]/h3'
ASSET_VEHICLE_TYPE_OPTION = '//*[text()="Truck"]'
ASSET_DEPOT_START_OPTIONS = '//*[text()="Boonrawd"]'